-- ============================================================
-- SEED — asset URLs
-- ============================================================
-- Generated by scripts/extract_assets.py from the source PDFs.
-- Do not edit by hand; re-run the script instead.
--
-- Paths are app-relative (public/assets/...). Point them at
-- Supabase Storage instead by changing the prefix here.
-- ============================================================

update public.mentors set image_url = '/assets/mentors/basma-khoja.png' where slug = 'basma-khoja';
update public.mentors set image_url = '/assets/mentors/anas-alsufyani.png' where slug = 'anas-alsufyani';
update public.mentors set image_url = '/assets/mentors/abduljawad-chowdhry.png' where slug = 'abduljawad-chowdhry';
update public.mentors set image_url = '/assets/mentors/abdullah-nobar.png' where slug = 'abdullah-nobar';
update public.mentor_organizations set org_logo_url = '/assets/mentors/basma-khoja-org1.png' where mentor_id = (select id from public.mentors where slug = 'basma-khoja') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/basma-khoja-org2.png' where mentor_id = (select id from public.mentors where slug = 'basma-khoja') and sort_order = 2;
update public.mentor_organizations set org_logo_url = '/assets/mentors/anas-alsufyani-org1.png' where mentor_id = (select id from public.mentors where slug = 'anas-alsufyani') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/anas-alsufyani-org2.png' where mentor_id = (select id from public.mentors where slug = 'anas-alsufyani') and sort_order = 2;
update public.mentor_organizations set org_logo_url = '/assets/mentors/abduljawad-chowdhry-org1.png' where mentor_id = (select id from public.mentors where slug = 'abduljawad-chowdhry') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/abduljawad-chowdhry-org2.png' where mentor_id = (select id from public.mentors where slug = 'abduljawad-chowdhry') and sort_order = 2;
update public.mentor_organizations set org_logo_url = '/assets/mentors/abdullah-nobar-org1.png' where mentor_id = (select id from public.mentors where slug = 'abdullah-nobar') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/abdullah-nobar-org2.png' where mentor_id = (select id from public.mentors where slug = 'abdullah-nobar') and sort_order = 2;
update public.mentors set image_url = '/assets/mentors/yazeed-almutairi.png' where slug = 'yazeed-almutairi';
update public.mentors set image_url = '/assets/mentors/abdullah-alqahtani.png' where slug = 'abdullah-alqahtani';
update public.mentors set image_url = '/assets/mentors/khalid-alkhudair.png' where slug = 'khalid-alkhudair';
update public.mentors set image_url = '/assets/mentors/muna-balhamar.png' where slug = 'muna-balhamar';
update public.mentor_organizations set org_logo_url = '/assets/mentors/yazeed-almutairi-org1.png' where mentor_id = (select id from public.mentors where slug = 'yazeed-almutairi') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/yazeed-almutairi-org2.png' where mentor_id = (select id from public.mentors where slug = 'yazeed-almutairi') and sort_order = 2;
update public.mentor_organizations set org_logo_url = '/assets/mentors/abdullah-alqahtani-org1.png' where mentor_id = (select id from public.mentors where slug = 'abdullah-alqahtani') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/abdullah-alqahtani-org2.png' where mentor_id = (select id from public.mentors where slug = 'abdullah-alqahtani') and sort_order = 2;
update public.mentor_organizations set org_logo_url = '/assets/mentors/khalid-alkhudair-org1.png' where mentor_id = (select id from public.mentors where slug = 'khalid-alkhudair') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/khalid-alkhudair-org2.png' where mentor_id = (select id from public.mentors where slug = 'khalid-alkhudair') and sort_order = 2;
update public.mentor_organizations set org_logo_url = '/assets/mentors/muna-balhamar-org1.png' where mentor_id = (select id from public.mentors where slug = 'muna-balhamar') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/muna-balhamar-org2.png' where mentor_id = (select id from public.mentors where slug = 'muna-balhamar') and sort_order = 2;
update public.mentors set image_url = '/assets/mentors/amin-ramadan.png' where slug = 'amin-ramadan';
update public.mentors set image_url = '/assets/mentors/ahmed-alzubairi.png' where slug = 'ahmed-alzubairi';
update public.mentors set image_url = '/assets/mentors/mohammed-almashjari.png' where slug = 'mohammed-almashjari';
update public.mentors set image_url = '/assets/mentors/sultan-alzahoufi.png' where slug = 'sultan-alzahoufi';
update public.mentor_organizations set org_logo_url = '/assets/mentors/amin-ramadan-org1.png' where mentor_id = (select id from public.mentors where slug = 'amin-ramadan') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/amin-ramadan-org2.png' where mentor_id = (select id from public.mentors where slug = 'amin-ramadan') and sort_order = 2;
update public.mentor_organizations set org_logo_url = '/assets/mentors/ahmed-alzubairi-org1.png' where mentor_id = (select id from public.mentors where slug = 'ahmed-alzubairi') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/mohammed-almashjari-org1.png' where mentor_id = (select id from public.mentors where slug = 'mohammed-almashjari') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/sultan-alzahoufi-org1.png' where mentor_id = (select id from public.mentors where slug = 'sultan-alzahoufi') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/sultan-alzahoufi-org2.png' where mentor_id = (select id from public.mentors where slug = 'sultan-alzahoufi') and sort_order = 2;
update public.mentors set image_url = '/assets/mentors/omran-yousef.png' where slug = 'omran-yousef';
update public.mentors set image_url = '/assets/mentors/adel-alsaedi.png' where slug = 'adel-alsaedi';
update public.mentor_organizations set org_logo_url = '/assets/mentors/omran-yousef-org1.png' where mentor_id = (select id from public.mentors where slug = 'omran-yousef') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/omran-yousef-org2.png' where mentor_id = (select id from public.mentors where slug = 'omran-yousef') and sort_order = 2;
update public.mentor_organizations set org_logo_url = '/assets/mentors/omran-yousef-org3.png' where mentor_id = (select id from public.mentors where slug = 'omran-yousef') and sort_order = 3;
update public.mentor_organizations set org_logo_url = '/assets/mentors/adel-alsaedi-org1.png' where mentor_id = (select id from public.mentors where slug = 'adel-alsaedi') and sort_order = 1;
update public.mentor_organizations set org_logo_url = '/assets/mentors/adel-alsaedi-org2.png' where mentor_id = (select id from public.mentors where slug = 'adel-alsaedi') and sort_order = 2;
update public.startups set logo_url = '/assets/startups/mabien.png' where slug = 'mabien';
update public.startups set logo_url = '/assets/startups/nanoclean.png' where slug = 'nanoclean';
update public.startups set logo_url = '/assets/startups/groupz.png' where slug = 'groupz';
update public.startups set logo_url = '/assets/startups/mustahaq.png' where slug = 'mustahaq';
update public.startups set logo_url = '/assets/startups/thella.png' where slug = 'thella';
update public.startups set logo_url = '/assets/startups/senoz-ai.png' where slug = 'senoz-ai';
update public.startups set logo_url = '/assets/startups/wound-care-ai.png' where slug = 'wound-care-ai';
update public.startups set logo_url = '/assets/startups/dithar.png' where slug = 'dithar';
update public.startups set logo_url = '/assets/startups/medirect.png' where slug = 'medirect';
update public.startups set logo_url = '/assets/startups/juthoor.png' where slug = 'juthoor';
update public.startups set logo_url = '/assets/startups/stetholink.png' where slug = 'stetholink';
update public.startups set logo_url = '/assets/startups/phagetech.png' where slug = 'phagetech';
update public.startups set logo_url = '/assets/startups/aquanova.png' where slug = 'aquanova';
update public.startups set logo_url = '/assets/startups/plstka.png' where slug = 'plstka';
update public.startups set logo_url = '/assets/startups/hader.png' where slug = 'hader';
update public.startups set logo_url = '/assets/startups/evinex.png' where slug = 'evinex';
update public.startups set logo_url = '/assets/startups/oprato.png' where slug = 'oprato';
update public.startups set logo_url = '/assets/startups/floraex.png' where slug = 'floraex';
update public.startups set logo_url = '/assets/startups/nkta.png' where slug = 'nkta';
update public.mentors set image_url = '/assets/mentors/sultan-alhayani.png' where slug = 'sultan-alhayani';
update public.mentors set image_url = '/assets/mentors/abdulrahman-hariri.png' where slug = 'abdulrahman-hariri';
