#!/usr/bin/env bash
# =============================================================================
# Build paste-ready SQL for the Supabase SQL Editor.
#
# The SQL Editor is not psql: it cannot run backslash meta-commands (\set, \if,
# \pset). Two seeds use them, so those are rewritten here rather than edited in
# place -- the psql versions stay working for the local test suite.
#
# Output (run in this order in the SQL Editor):
#   supabase/deploy/01_schema.sql       all 11 migrations
#   supabase/deploy/02_data.sql         startups, mentors, orgs, assets, session
#   supabase/deploy/03_issue_codes.sql  generate + PRINT the 19 access codes
#
#   ./scripts/build-deploy-sql.sh
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/supabase/deploy"
mkdir -p "$OUT"

# ---- 1. schema -------------------------------------------------------------
{
  cat <<'HDR'
-- ============================================================================
-- WJIncubator — SCHEMA (step 1 of 3)
-- ============================================================================
-- Generated by scripts/build-deploy-sql.sh. Do not edit by hand.
--
-- Paste this whole file into the Supabase SQL Editor and press Run. It applies
-- all 11 migrations in order: extensions, tables, constraints, helpers, RLS,
-- and every RPC.
--
-- Safe to run on an EMPTY project only. It creates objects rather than merging.
-- ============================================================================

HDR
  for f in "$ROOT"/supabase/migrations/*.sql; do
    echo "-- ==================== $(basename "$f") ===================="
    cat "$f"
    echo
  done
} > "$OUT/01_schema.sql"

# ---- 2. data ---------------------------------------------------------------
{
  cat <<'HDR'
-- ============================================================================
-- WJIncubator — DATA (step 2 of 3)
-- ============================================================================
-- Startups, mentors, mentor organisations, image URLs, and ONE draft session.
-- Every value is transcribed from the two source PDFs.
--
-- The session is created in `draft` with NO date, NO assigned mentors and NO
-- slots. Those are admin decisions made in the UI -- the session physically
-- cannot be opened without a date (sessions_open_needs_date).
--
-- Idempotent: re-running updates profiles in place and never duplicates.
-- Access codes are NOT set here -- that is step 3.
-- ============================================================================

HDR
  for f in 01_startups 02_mentors 03_mentor_organizations 06_asset_urls; do
    echo "-- ==================== ${f}.sql ===================="
    cat "$ROOT/supabase/seed/${f}.sql"
    echo
  done

  # 04_session.sql rewritten: the psql \if block that makes the date optional
  # has no SQL Editor equivalent, so the date is simply left NULL for the admin
  # to set in the UI.
  cat <<'SESSION'
-- ==================== session (draft, no date) ====================
-- Rewritten from 04_session.sql for the SQL Editor: the original uses psql
-- \if/\set to accept an optional -v session_date. Here the date is left NULL
-- and the admin sets it in Admin -> الجلسة before opening the session.

insert into public.sessions
  (name, session_date, starts_at, ends_at, slot_minutes,
   max_bookings_per_startup, allow_startup_cancellation, block_duplicate_mentor, status)
select
  'جلسات الإرشاد — WJIncubator',
  null,           -- admin sets the real event date in the UI
  time '17:00',   -- 5 PM  — the slot generator's start
  time '19:00',   -- 7 PM  — the slot generator's end
  20,             -- 20-minute intervals
  3,              -- max 3 confirmed bookings per startup
  false,          -- startup self-cancellation OFF
  true,           -- never the same mentor twice
  'draft'
where not exists (
  select 1 from public.sessions where name = 'جلسات الإرشاد — WJIncubator'
);

select s.name,
       coalesce(s.session_date::text, '(غير محدد — يحدده المشرف)') as session_date,
       s.status,
       s.starts_at, s.ends_at, s.slot_minutes,
       s.max_bookings_per_startup as cap,
       (select count(*) from public.startups) as startups,
       (select count(*) from public.mentors)  as mentors
  from public.sessions s
 where s.name = 'جلسات الإرشاد — WJIncubator';
SESSION
} > "$OUT/02_data.sql"

# ---- 3. access codes -------------------------------------------------------
{
  cat <<'HDR'
-- ============================================================================
-- WJIncubator — ACCESS CODES (step 3 of 3)
-- ============================================================================
--   *** THE CODES ARE SHOWN ONCE. COPY THE RESULT BEFORE LEAVING THIS PAGE. ***
--
-- Codes are stored as bcrypt hashes and cannot be read back afterwards. If a
-- company loses its code, reset it from Admin -> الشركات, which reveals a new
-- one once.
--
-- Only startups WITHOUT a code are touched, so re-running will not invalidate
-- codes already handed out.
-- ============================================================================

HDR
  # Same logic as 05_issue_codes.sql, minus the psql meta-commands.
  sed '/^\\/d' "$ROOT/supabase/seed/05_issue_codes.sql"
} > "$OUT/03_issue_codes.sql"

echo "wrote:"
for f in 01_schema 02_data 03_issue_codes; do
  printf '  %-22s %5s lines\n' "$f.sql" "$(wc -l < "$OUT/$f.sql")"
done
