-- ============================================================================
-- WJIncubator — SCHEMA (step 1 of 3)
-- ============================================================================
-- Generated by scripts/build-deploy-sql.sh. Do not edit by hand.
--
-- Paste this whole file into the Supabase SQL Editor and press Run. It applies
-- all 11 migrations in order: extensions, tables, constraints, helpers, RLS,
-- and every RPC.
--
-- Safe to run on an EMPTY project only. It creates objects rather than merging.
-- ============================================================================

-- ==================== 0001_extensions.sql ====================
-- ============================================================================
-- 0001 — Extensions
-- ============================================================================
-- pgcrypto provides gen_random_uuid() and the bcrypt crypt()/gen_salt() pair
-- used to hash startup access codes. It lives in the `extensions` schema so
-- that SECURITY DEFINER functions can run with `search_path = ''` and still
-- reach it by explicit qualification — an empty search_path is what stops a
-- caller from shadowing our function names with their own.
-- ============================================================================

create schema if not exists extensions;

create extension if not exists pgcrypto with schema extensions;

grant usage on schema extensions to public;

-- ==================== 0002_types_tables.sql ====================
-- ============================================================================
-- 0002 — Enums and tables
-- ============================================================================
-- Model shape:
--
--   sessions ──< session_mentors ──< slots ──< bookings
--                      │                          │
--                   mentors                    startups
--
-- A *session* is one bookable event (date, time grid, per-session rules).
-- Mentor participation is per-session and admin-controlled, so all mentor
-- profiles can live in `mentors` while only the assigned, active ones appear
-- to startups. Nothing about the roster size is encoded in the schema — a
-- future event needs new rows, not new code.
-- ============================================================================

create type public.session_status as enum ('draft', 'open', 'closed');
create type public.slot_status    as enum ('open', 'closed');
create type public.booking_status as enum ('confirmed', 'cancelled');
create type public.actor_kind     as enum ('startup', 'admin', 'system');

-- ---------------------------------------------------------------------------
-- startups — the 19 participating companies (source: Incubator_Startup_Profiles.pdf)
-- ---------------------------------------------------------------------------
create table public.startups (
  id                    uuid primary key default gen_random_uuid(),
  sort_order            integer not null default 0,
  name_ar               text not null,
  name_en               text not null,
  slug                  text not null unique,
  logo_url              text,
  founder_name          text,
  founder_role          text,
  description           text,
  stage                 text,
  hq                    text,
  linkedin_url          text,
  sector                text,

  -- bcrypt hash of the private 4-digit code. NULL until codes are issued, so
  -- the roster can be seeded before the codes exist. Never selectable by the
  -- client: no RLS policy exposes this table to anon at all.
  access_code_hash      text,

  is_active             boolean not null default true,

  -- Per-startup override of the session's booking cap. NULL = use the session
  -- default, which is where the "3 bookings" rule actually lives.
  max_bookings_override integer check (max_bookings_override is null or max_bookings_override >= 0),

  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- mentors — every mentor profile from the source file
-- ---------------------------------------------------------------------------
create table public.mentors (
  id                 uuid primary key default gen_random_uuid(),
  sort_order         integer not null default 0,
  -- Stable natural key: makes seeding idempotent and gives extracted image
  -- assets a predictable filename to map onto.
  slug               text not null unique,
  name_ar            text not null,
  name_en            text,
  image_url          text,
  bio                text,
  role               text,

  -- Verbatim from the source deck ("الخميس 5–7", "فترتين", "السبت").
  -- Display metadata only — nothing branches on this value.
  availability_label text,

  -- Global archive flag. Participation in a given event is decided by
  -- session_mentors, not by this column.
  is_active          boolean not null default true,

  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create table public.mentor_organizations (
  id            uuid primary key default gen_random_uuid(),
  mentor_id     uuid not null references public.mentors (id) on delete cascade,
  org_name      text not null,
  org_logo_url  text,
  sort_order    integer not null default 0
);

-- ---------------------------------------------------------------------------
-- sessions — one bookable event. All tunable rules live here, not in code.
-- ---------------------------------------------------------------------------
create table public.sessions (
  id                         uuid primary key default gen_random_uuid(),
  name                       text not null,

  -- Configurable: left NULL until the event is scheduled. A session cannot be
  -- opened without it (see the CHECK below).
  session_date               date,

  starts_at                  time not null default '17:00',
  ends_at                    time not null default '19:00',
  slot_minutes               integer not null default 20 check (slot_minutes between 5 and 180),

  -- The confirmed-booking cap. This is the "max 3" rule.
  max_bookings_per_startup   integer not null default 3 check (max_bookings_per_startup >= 0),

  -- Per-event policy switches, so these stay decisions rather than edits.
  allow_startup_cancellation boolean not null default false,
  block_duplicate_mentor     boolean not null default true,

  status                     session_status not null default 'draft',
  created_at                 timestamptz not null default now(),
  updated_at                 timestamptz not null default now(),

  constraint sessions_time_order check (ends_at > starts_at),
  constraint sessions_open_needs_date check (status = 'draft' or session_date is not null)
);

comment on column public.sessions.max_bookings_per_startup is
  'Confirmed-booking cap per startup for this session. Overridable per startup via startups.max_bookings_override.';

-- ---------------------------------------------------------------------------
-- session_mentors — which mentors take part, and whether they are active.
-- This is the table the admin drives; the startup view reads through it.
-- ---------------------------------------------------------------------------
create table public.session_mentors (
  id          uuid primary key default gen_random_uuid(),
  session_id  uuid not null references public.sessions (id) on delete cascade,
  mentor_id   uuid not null references public.mentors (id) on delete restrict,
  is_active   boolean not null default true,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),

  unique (session_id, mentor_id)
);

-- ---------------------------------------------------------------------------
-- slots
-- ---------------------------------------------------------------------------
-- The FK targets session_mentors rather than mentors, so a slot cannot exist
-- for a mentor who was never assigned to that session. Unassigning a mentor
-- removes their slots by cascade instead of leaving orphans behind.
--
-- `status` is open/closed ONLY. Booked-ness is derived from the existence of a
-- confirmed booking — a stored "booked" flag is the classic desync bug, where
-- one cancellation that forgets to reset it kills the slot for the rest of the
-- event. Admin close/reopen is a genuinely separate axis, which is why it is
-- the thing that gets stored.
-- ---------------------------------------------------------------------------
create table public.slots (
  id          uuid primary key default gen_random_uuid(),
  session_id  uuid not null,
  mentor_id   uuid not null,
  start_time  time not null,
  end_time    time not null,
  status      slot_status not null default 'open',
  created_at  timestamptz not null default now(),

  constraint slots_time_order check (end_time > start_time),

  constraint slots_session_mentor_fk
    foreign key (session_id, mentor_id)
    references public.session_mentors (session_id, mentor_id) on delete cascade,

  -- One slot per mentor per start time within a session.
  constraint slots_unique_per_mentor_time unique (session_id, mentor_id, start_time),

  -- Target for the bookings composite FK below. Makes the denormalised columns
  -- on `bookings` provably consistent with the slot they point at.
  constraint slots_identity_unique unique (id, session_id, mentor_id, start_time)
);

-- ---------------------------------------------------------------------------
-- bookings
-- ---------------------------------------------------------------------------
-- session_id / mentor_id / start_time are denormalised so the "no two bookings
-- at the same time" and "not the same mentor twice" rules can be expressed as
-- plain indexes. The composite FK below locks those copies to the slot they
-- came from, so they cannot drift.
-- ---------------------------------------------------------------------------
create table public.bookings (
  id            uuid primary key default gen_random_uuid(),
  startup_id    uuid not null references public.startups (id) on delete restrict,
  slot_id       uuid not null,
  session_id    uuid not null,
  mentor_id     uuid not null,
  start_time    time not null,
  status        booking_status not null default 'confirmed',
  created_at    timestamptz not null default now(),
  cancelled_at  timestamptz,
  cancelled_by  actor_kind,
  cancel_reason text,

  constraint bookings_slot_fk
    foreign key (slot_id, session_id, mentor_id, start_time)
    references public.slots (id, session_id, mentor_id, start_time) on delete restrict,

  -- A cancelled booking must carry a timestamp, and a live one must not.
  constraint bookings_cancel_consistency
    check ((status = 'cancelled') = (cancelled_at is not null))
);

-- ---------------------------------------------------------------------------
-- startup_auth_tokens — opaque session tokens issued after a code check.
-- Startups are not Supabase Auth users; admins are.
-- ---------------------------------------------------------------------------
create table public.startup_auth_tokens (
  token        text primary key,
  startup_id   uuid not null references public.startups (id) on delete cascade,
  created_at   timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at   timestamptz not null,
  revoked_at   timestamptz
);

-- ---------------------------------------------------------------------------
-- admin_users — membership table gating the admin surface. A valid Supabase
-- Auth login that is not listed here has no admin access.
-- ---------------------------------------------------------------------------
create table public.admin_users (
  user_id      uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  created_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- login_attempts — feeds the brute-force throttle. A 4-digit code is only
-- 10,000 combinations, so unthrottled guessing is a real attack, not a
-- theoretical one.
-- ---------------------------------------------------------------------------
create table public.login_attempts (
  id         bigserial primary key,
  startup_id uuid,
  succeeded  boolean not null,
  created_at timestamptz not null default now()
);

create table public.audit_log (
  id         bigserial primary key,
  actor      actor_kind not null,
  actor_id   text,
  action     text not null,
  entity     text,
  entity_id  uuid,
  detail     jsonb,
  created_at timestamptz not null default now()
);

-- ==================== 0003_constraints_indexes.sql ====================
-- ============================================================================
-- 0003 — Rule-enforcing indexes and supporting indexes
-- ============================================================================
-- How the booking rules are split between indexes and the booking RPC:
--
--   CROSS-STARTUP rules must be indexes. Two different startups racing for the
--   same slot are two different transactions touching different startup rows,
--   so only a shared constraint can arbitrate. That is "one confirmed booking
--   per slot".
--
--   PER-STARTUP rules (booking cap, time clash, duplicate mentor) are decided
--   inside book_slot() while holding a row lock on that startup. The lock fully
--   serialises one startup's concurrent attempts, so a count taken under it
--   cannot be stale. Two of these also get an index anyway, as defence in
--   depth. The cap and the duplicate-mentor rule are configurable per session,
--   which a partial index cannot express — those stay RPC-enforced, and the
--   row lock is what makes that airtight rather than hopeful.
-- ============================================================================

-- RULE: a slot can hold at most one confirmed booking.
-- This is the one that arbitrates between competing startups. Cancelled rows
-- are excluded, so a cancelled booking frees the slot with no extra work.
create unique index bookings_one_confirmed_per_slot
  on public.bookings (slot_id)
  where status = 'confirmed';

-- RULE: a startup cannot hold two confirmed bookings at the same moment.
create unique index bookings_no_time_clash
  on public.bookings (startup_id, session_id, start_time)
  where status = 'confirmed';

-- Supporting indexes for the dashboard and admin queries.
create index bookings_by_startup    on public.bookings (startup_id, session_id) where status = 'confirmed';
create index bookings_by_session    on public.bookings (session_id, start_time);
create index bookings_by_mentor     on public.bookings (mentor_id, session_id)  where status = 'confirmed';
create index slots_by_session       on public.slots (session_id, start_time);
create index slots_by_mentor        on public.slots (session_id, mentor_id);
create index session_mentors_active on public.session_mentors (session_id) where is_active;
create index mentor_orgs_by_mentor  on public.mentor_organizations (mentor_id, sort_order);

-- At most one session may be `open` at a time. "The current session" is
-- therefore a fact the database guarantees, not a convention the app hopes for.
create unique index sessions_only_one_open
  on public.sessions ((status))
  where status = 'open';

-- Token lookups and expiry sweeps.
create index startup_auth_tokens_by_startup on public.startup_auth_tokens (startup_id);
create index startup_auth_tokens_expiry     on public.startup_auth_tokens (expires_at);

-- Throttle window lookups.
create index login_attempts_recent on public.login_attempts (startup_id, created_at desc);

create index audit_log_recent on public.audit_log (created_at desc);

-- Keep `updated_at` honest without every writer having to remember.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger startups_touch before update on public.startups
  for each row execute function public.touch_updated_at();
create trigger mentors_touch before update on public.mentors
  for each row execute function public.touch_updated_at();
create trigger sessions_touch before update on public.sessions
  for each row execute function public.touch_updated_at();

-- ==================== 0004_helpers.sql ====================
-- ============================================================================
-- 0004 — Internal helpers
-- ============================================================================
-- Every function here is SECURITY DEFINER with `search_path = ''`. The empty
-- search path is deliberate: it forces full qualification of every identifier,
-- so a caller cannot shadow a table or function name and have our elevated
-- function resolve to theirs instead.
-- ============================================================================

-- Is the current Supabase Auth user an admin?
-- SECURITY DEFINER because admin_users is itself behind RLS — a plain query
-- would be filtered by the very policy that calls this.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users a where a.user_id = auth.uid()
  );
$$;

-- The single open session, or NULL. Guaranteed unique by sessions_only_one_open.
create or replace function public.current_session_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select s.id from public.sessions s where s.status = 'open' limit 1;
$$;

-- Resolve an opaque startup token to a startup id, or NULL if the token is
-- unknown, expired or revoked. Touches last_seen_at so idle sessions are
-- visible to the admin.
create or replace function public.startup_id_from_token(p_token text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_startup_id uuid;
begin
  if p_token is null or length(p_token) < 20 then
    return null;
  end if;

  update public.startup_auth_tokens
     set last_seen_at = now()
   where token = p_token
     and revoked_at is null
     and expires_at > now()
  returning startup_id into v_startup_id;

  return v_startup_id;
end;
$$;

-- The booking cap that actually applies: the session default unless this
-- startup carries an explicit override.
create or replace function public.effective_max_bookings(p_startup_id uuid, p_session_id uuid)
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(st.max_bookings_override, se.max_bookings_per_startup)
    from public.startups st
    cross join public.sessions se
   where st.id = p_startup_id
     and se.id = p_session_id;
$$;

-- Uniform result envelopes, so every RPC speaks the same shape and the client
-- can map `code` to an Arabic message in one place.
create or replace function public.rpc_error(p_code text, p_detail jsonb default null)
returns jsonb
language sql
immutable
set search_path = ''
as $$
  select jsonb_build_object('ok', false, 'code', p_code) ||
         coalesce(jsonb_build_object('detail', p_detail), '{}'::jsonb);
$$;

create or replace function public.rpc_ok(p_data jsonb default '{}'::jsonb)
returns jsonb
language sql
immutable
set search_path = ''
as $$
  select jsonb_build_object('ok', true) || coalesce(p_data, '{}'::jsonb);
$$;

create or replace function public.write_audit(
  p_actor public.actor_kind,
  p_actor_id text,
  p_action text,
  p_entity text default null,
  p_entity_id uuid default null,
  p_detail jsonb default null
)
returns void
language sql
security definer
set search_path = ''
as $$
  insert into public.audit_log (actor, actor_id, action, entity, entity_id, detail)
  values (p_actor, p_actor_id, p_action, p_entity, p_entity_id, p_detail);
$$;

-- ==================== 0005_rls.sql ====================
-- ============================================================================
-- 0005 — Row Level Security
-- ============================================================================
-- Posture: RLS on for every table, and NO policy for `anon` anywhere. In
-- Postgres, RLS with no matching policy denies — so the browser's anon key can
-- read and write exactly nothing directly. All startup-facing access goes
-- through SECURITY DEFINER RPCs, which is what lets the database check the
-- rules itself instead of trusting the caller.
--
-- Consequence worth stating plainly: possession of the anon key grants nothing.
-- It is a routing credential, not an authorisation one.
--
-- Admins are real Supabase Auth users and DO get table policies, because the
-- admin UI benefits from ordinary reads and the writes still funnel through
-- RPCs that audit.
-- ============================================================================

alter table public.startups             enable row level security;
alter table public.mentors              enable row level security;
alter table public.mentor_organizations enable row level security;
alter table public.sessions             enable row level security;
alter table public.session_mentors      enable row level security;
alter table public.slots                enable row level security;
alter table public.bookings             enable row level security;
alter table public.startup_auth_tokens  enable row level security;
alter table public.admin_users          enable row level security;
alter table public.login_attempts       enable row level security;
alter table public.audit_log            enable row level security;

-- Belt and braces: even if a policy were added by mistake, the anon role has
-- no table privileges to exercise. Function EXECUTE is granted explicitly in
-- the RPC migrations.
revoke all on all tables in schema public from anon, authenticated;

-- The access-code hash must never be readable, by anyone, through any path.
-- Column-level revoke means even a future over-broad policy cannot leak it.
revoke select (access_code_hash) on public.startups from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Admin read policies
-- ---------------------------------------------------------------------------
create policy admin_read_startups on public.startups
  for select to authenticated using (public.is_admin());

create policy admin_read_mentors on public.mentors
  for select to authenticated using (public.is_admin());

create policy admin_read_mentor_orgs on public.mentor_organizations
  for select to authenticated using (public.is_admin());

create policy admin_read_sessions on public.sessions
  for select to authenticated using (public.is_admin());

create policy admin_read_session_mentors on public.session_mentors
  for select to authenticated using (public.is_admin());

create policy admin_read_slots on public.slots
  for select to authenticated using (public.is_admin());

create policy admin_read_bookings on public.bookings
  for select to authenticated using (public.is_admin());

create policy admin_read_audit on public.audit_log
  for select to authenticated using (public.is_admin());

create policy admin_read_login_attempts on public.login_attempts
  for select to authenticated using (public.is_admin());

-- An admin may see that startup sessions exist (for support: "are they logged
-- in?") but the token column is revoked below so the value itself stays opaque.
create policy admin_read_tokens on public.startup_auth_tokens
  for select to authenticated using (public.is_admin());

revoke select (token) on public.startup_auth_tokens from authenticated;

-- Admins may see the admin roster.
create policy admin_read_admins on public.admin_users
  for select to authenticated using (public.is_admin());

-- ---------------------------------------------------------------------------
-- Deliberately absent: INSERT / UPDATE / DELETE policies.
--
-- Nobody writes to these tables directly — not even an admin. Every mutation
-- goes through an RPC that validates, audits, and (for bookings) holds the
-- right locks. Leaving the write path out of RLS entirely means there is no
-- second, unaudited way in.
-- ---------------------------------------------------------------------------

grant select on public.mentors, public.mentor_organizations,
                public.sessions, public.session_mentors, public.slots,
                public.bookings, public.audit_log, public.login_attempts,
                public.admin_users
  to authenticated;

-- ---------------------------------------------------------------------------
-- Secret-bearing tables get COLUMN-level grants, never table-level.
--
-- This is not stylistic. In Postgres a table-level GRANT SELECT confers every
-- column, and a later REVOKE SELECT (col) does NOT carve one back out — column
-- revokes only touch column-level grants. Granting the whole table and then
-- revoking the secret column silently leaves it readable. Enumerating the
-- allowed columns is the only construction that actually withholds one.
--
-- Omitted deliberately:
--   startups.access_code_hash      — the bcrypt hash of a startup's code
--   startup_auth_tokens.token      — a live session bearer token
-- Neither is readable by ANY role through ANY path. Codes are verified inside
-- startup_login(); tokens are issued there and never read back.
-- ---------------------------------------------------------------------------
grant select (
  id, sort_order, name_ar, name_en, slug, logo_url,
  founder_name, founder_role, description, stage, hq,
  linkedin_url, sector, is_active, max_bookings_override,
  created_at, updated_at
) on public.startups to authenticated;

grant select (
  startup_id, created_at, last_seen_at, expires_at, revoked_at
) on public.startup_auth_tokens to authenticated;

-- ==================== 0006_rpc_startup_auth.sql ====================
-- ============================================================================
-- 0006 — Startup authentication RPCs
-- ============================================================================
-- Startups do not have Supabase Auth accounts. They pick their company from a
-- list and enter a private 4-digit code, which is verified HERE, server-side,
-- against a bcrypt hash. The code never leaves the database and the hash never
-- leaves the server, so no amount of client inspection reveals another
-- company's code.
--
-- A 4-digit code is 10,000 combinations — small enough that guessing is a real
-- attack. `startup_login` therefore throttles per startup.
-- ============================================================================

-- Login dropdown source. Returns identity and branding only; there is no
-- column here that could hint at a code.
create or replace function public.list_startups()
returns table (
  id        uuid,
  name_ar   text,
  name_en   text,
  logo_url  text,
  is_active boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  select s.id, s.name_ar, s.name_en, s.logo_url, s.is_active
    from public.startups s
   order by s.sort_order, s.name_ar;
$$;

-- ---------------------------------------------------------------------------
-- startup_login
-- ---------------------------------------------------------------------------
-- Failure codes: INVALID_CODE, STARTUP_INACTIVE, TOO_MANY_ATTEMPTS, BAD_FORMAT
--
-- "no code set" and "wrong code" both return INVALID_CODE on purpose — telling
-- them apart would let someone map which startups are provisioned.
-- ---------------------------------------------------------------------------
create or replace function public.startup_login(p_startup_id uuid, p_code text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_startup    public.startups%rowtype;
  v_failures   integer;
  v_token      text;
  v_ttl        interval := interval '12 hours';
begin
  -- Codes are TEXT, not integers: '0042' must survive as '0042'.
  if p_code is null or p_code !~ '^[0-9]{4}$' then
    return public.rpc_error('BAD_FORMAT');
  end if;

  select * into v_startup from public.startups where id = p_startup_id;
  if not found then
    return public.rpc_error('INVALID_CODE');
  end if;

  -- Throttle: 5 failures in 15 minutes locks this startup out of further
  -- attempts. Counted per startup, which is the thing being guessed.
  select count(*) into v_failures
    from public.login_attempts
   where startup_id = p_startup_id
     and succeeded = false
     and created_at > now() - interval '15 minutes';

  if v_failures >= 5 then
    return public.rpc_error('TOO_MANY_ATTEMPTS');
  end if;

  if v_startup.access_code_hash is null
     or extensions.crypt(p_code, v_startup.access_code_hash) <> v_startup.access_code_hash then
    insert into public.login_attempts (startup_id, succeeded) values (p_startup_id, false);
    return public.rpc_error('INVALID_CODE');
  end if;

  -- Correct code, but the company is switched off.
  if not v_startup.is_active then
    insert into public.login_attempts (startup_id, succeeded) values (p_startup_id, true);
    return public.rpc_error('STARTUP_INACTIVE');
  end if;

  v_token := encode(extensions.gen_random_bytes(32), 'hex');

  insert into public.startup_auth_tokens (token, startup_id, expires_at)
  values (v_token, p_startup_id, now() + v_ttl);

  insert into public.login_attempts (startup_id, succeeded) values (p_startup_id, true);
  perform public.write_audit('startup', p_startup_id::text, 'login', 'startups', p_startup_id, null);

  return public.rpc_ok(jsonb_build_object(
    'token',      v_token,
    'expires_at', now() + v_ttl,
    'startup',    jsonb_build_object(
      'id',       v_startup.id,
      'name_ar',  v_startup.name_ar,
      'name_en',  v_startup.name_en,
      'logo_url', v_startup.logo_url
    )
  ));
end;
$$;

create or replace function public.startup_logout(p_token text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  update public.startup_auth_tokens
     set revoked_at = now()
   where token = p_token
     and revoked_at is null;
  return public.rpc_ok();
end;
$$;

-- ---------------------------------------------------------------------------
-- Grants. These four are the ENTIRE public surface for an unauthenticated
-- client: list the companies, log in, log out. Nothing else is reachable.
-- ---------------------------------------------------------------------------
grant execute on function public.list_startups()                to anon, authenticated;
grant execute on function public.startup_login(uuid, text)      to anon, authenticated;
grant execute on function public.startup_logout(text)           to anon, authenticated;

-- ==================== 0007_rpc_startup_booking.sql ====================
-- ============================================================================
-- 0007 — Startup booking RPCs
-- ============================================================================

-- ---------------------------------------------------------------------------
-- get_startup_dashboard — everything the dashboard needs, in one round trip.
-- ---------------------------------------------------------------------------
-- Slot state is reported as one of: available | booked | mine | closed.
-- "booked" deliberately carries no identity: a startup learns that a slot is
-- taken, never by whom. That is also why this is an RPC rather than a
-- subscribable view — a realtime payload of the bookings table would leak it.
-- ---------------------------------------------------------------------------
-- VOLATILE, not STABLE: this reads like a pure query, but startup_id_from_token()
-- writes — it touches last_seen_at on every call. PostgREST runs STABLE functions
-- in a READ ONLY transaction, so marking this STABLE makes every single call fail
-- with SQLSTATE 25006 "cannot execute UPDATE in a read-only transaction", taking
-- the whole startup dashboard down. The other three token-consuming RPCs
-- (startup_session_info, book_slot, cancel_my_booking) are volatile for this
-- same reason.
create or replace function public.get_startup_dashboard(p_token text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_startup_id uuid;
  v_startup    public.startups%rowtype;
  v_session    public.sessions%rowtype;
  v_limit      integer;
  v_used       integer;
  v_mentors    jsonb;
  v_bookings   jsonb;
begin
  v_startup_id := public.startup_id_from_token(p_token);
  if v_startup_id is null then
    return public.rpc_error('INVALID_SESSION');
  end if;

  select * into v_startup from public.startups where id = v_startup_id;

  select * into v_session from public.sessions where status = 'open';
  if not found then
    -- No event is open. A real state, not an error the user caused.
    return public.rpc_ok(jsonb_build_object(
      'startup', jsonb_build_object(
        'id', v_startup.id, 'name_ar', v_startup.name_ar,
        'name_en', v_startup.name_en, 'logo_url', v_startup.logo_url,
        'is_active', v_startup.is_active),
      'session',  null,
      'quota',    null,
      'bookings', '[]'::jsonb,
      'mentors',  '[]'::jsonb
    ));
  end if;

  v_limit := public.effective_max_bookings(v_startup_id, v_session.id);

  select count(*) into v_used
    from public.bookings b
   where b.startup_id = v_startup_id
     and b.session_id = v_session.id
     and b.status = 'confirmed';

  -- Mentors active for THIS session only, each with their slots.
  select coalesce(jsonb_agg(m_row order by m_row->>'sort_order'), '[]'::jsonb)
    into v_mentors
  from (
    select jsonb_build_object(
             'id',                 m.id,
             'name_ar',            m.name_ar,
             'name_en',            m.name_en,
             'image_url',          m.image_url,
             'bio',                m.bio,
             'role',               m.role,
             'availability_label', m.availability_label,
             'sort_order',         lpad(sm.sort_order::text, 6, '0'),
             'organizations',      (
               select coalesce(jsonb_agg(jsonb_build_object(
                        'name', o.org_name, 'logo_url', o.org_logo_url
                      ) order by o.sort_order), '[]'::jsonb)
                 from public.mentor_organizations o
                where o.mentor_id = m.id
             ),
             'slots', (
               select coalesce(jsonb_agg(jsonb_build_object(
                        'id',         sl.id,
                        'start_time', to_char(sl.start_time, 'HH24:MI'),
                        'end_time',   to_char(sl.end_time,   'HH24:MI'),
                        'state',
                          case
                            when sl.status = 'closed'            then 'closed'
                            when b.startup_id = v_startup_id     then 'mine'
                            when b.id is not null                then 'booked'
                            else 'available'
                          end
                      ) order by sl.start_time), '[]'::jsonb)
                 from public.slots sl
                 left join public.bookings b
                        on b.slot_id = sl.id and b.status = 'confirmed'
                where sl.session_id = v_session.id
                  and sl.mentor_id  = m.id
             )
           ) as m_row
      from public.session_mentors sm
      join public.mentors m on m.id = sm.mentor_id
     where sm.session_id = v_session.id
       and sm.is_active
       and m.is_active
  ) t;

  select coalesce(jsonb_agg(jsonb_build_object(
           'id',           b.id,
           'mentor_id',    b.mentor_id,
           'mentor_name',  m.name_ar,
           'mentor_image', m.image_url,
           'start_time',   to_char(b.start_time, 'HH24:MI'),
           'end_time',     to_char(sl.end_time,  'HH24:MI'),
           'status',       b.status,
           'created_at',   b.created_at
         ) order by b.start_time), '[]'::jsonb)
    into v_bookings
    from public.bookings b
    join public.mentors m on m.id = b.mentor_id
    join public.slots  sl on sl.id = b.slot_id
   where b.startup_id = v_startup_id
     and b.session_id = v_session.id
     and b.status = 'confirmed';

  return public.rpc_ok(jsonb_build_object(
    'startup', jsonb_build_object(
      'id', v_startup.id, 'name_ar', v_startup.name_ar,
      'name_en', v_startup.name_en, 'logo_url', v_startup.logo_url,
      'is_active', v_startup.is_active),
    'session', jsonb_build_object(
      'id', v_session.id, 'name', v_session.name,
      'session_date', v_session.session_date,
      'allow_cancellation', v_session.allow_startup_cancellation),
    'quota', jsonb_build_object(
      'limit', v_limit, 'used', v_used, 'remaining', greatest(v_limit - v_used, 0)),
    'bookings', v_bookings,
    'mentors',  v_mentors
  ));
end;
$$;

-- ---------------------------------------------------------------------------
-- book_slot — the one write path for startups.
-- ---------------------------------------------------------------------------
-- Failure codes:
--   INVALID_SESSION · STARTUP_INACTIVE · SLOT_NOT_FOUND · SLOT_CLOSED
--   SESSION_CLOSED  · MENTOR_INACTIVE  · SLOT_TAKEN     · LIMIT_REACHED
--   TIME_CONFLICT   · MENTOR_ALREADY_BOOKED
--
-- Locking: the startup row is locked BEFORE the slot row, always in that
-- order. Two startups racing the same slot contend on the slot; one startup
-- double-clicking contends on itself. A fixed lock order means no cycle, so
-- these can never deadlock. Holding the startup lock is what makes the
-- per-startup counts below safe to read with a plain SELECT.
-- ---------------------------------------------------------------------------
create or replace function public.book_slot(p_token text, p_slot_id uuid)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_startup_id uuid;
  v_startup    public.startups%rowtype;
  v_slot       public.slots%rowtype;
  v_session    public.sessions%rowtype;
  v_limit      integer;
  v_used       integer;
  v_booking_id uuid;
begin
  v_startup_id := public.startup_id_from_token(p_token);
  if v_startup_id is null then
    return public.rpc_error('INVALID_SESSION');
  end if;

  -- (1) Lock this startup. Serialises its own concurrent attempts.
  select * into v_startup from public.startups where id = v_startup_id for update;
  if not v_startup.is_active then
    return public.rpc_error('STARTUP_INACTIVE');
  end if;

  -- (2) Lock the slot. Arbitrates between competing startups.
  select * into v_slot from public.slots where id = p_slot_id for update;
  if not found then
    return public.rpc_error('SLOT_NOT_FOUND');
  end if;
  if v_slot.status <> 'open' then
    return public.rpc_error('SLOT_CLOSED');
  end if;

  -- (3) The slot must belong to the session that is currently open.
  select * into v_session from public.sessions where id = v_slot.session_id;
  if v_session.status <> 'open' then
    return public.rpc_error('SESSION_CLOSED');
  end if;

  -- (4) Mentor must be assigned to this session, active for it, and not archived.
  if not exists (
    select 1
      from public.session_mentors sm
      join public.mentors m on m.id = sm.mentor_id
     where sm.session_id = v_slot.session_id
       and sm.mentor_id  = v_slot.mentor_id
       and sm.is_active
       and m.is_active
  ) then
    return public.rpc_error('MENTOR_INACTIVE');
  end if;

  -- (5) Already taken? (The unique index re-checks this at INSERT.)
  if exists (
    select 1 from public.bookings b
     where b.slot_id = v_slot.id and b.status = 'confirmed'
  ) then
    return public.rpc_error('SLOT_TAKEN');
  end if;

  -- (6) Booking cap — session default, or this startup's override.
  v_limit := public.effective_max_bookings(v_startup_id, v_slot.session_id);
  select count(*) into v_used
    from public.bookings b
   where b.startup_id = v_startup_id
     and b.session_id = v_slot.session_id
     and b.status = 'confirmed';
  if v_used >= v_limit then
    return public.rpc_error('LIMIT_REACHED', jsonb_build_object('limit', v_limit));
  end if;

  -- (7) No two bookings at the same moment.
  if exists (
    select 1 from public.bookings b
     where b.startup_id = v_startup_id
       and b.session_id = v_slot.session_id
       and b.start_time = v_slot.start_time
       and b.status = 'confirmed'
  ) then
    return public.rpc_error('TIME_CONFLICT');
  end if;

  -- (8) Same mentor twice — per-session policy.
  if v_session.block_duplicate_mentor and exists (
    select 1 from public.bookings b
     where b.startup_id = v_startup_id
       and b.session_id = v_slot.session_id
       and b.mentor_id  = v_slot.mentor_id
       and b.status = 'confirmed'
  ) then
    return public.rpc_error('MENTOR_ALREADY_BOOKED');
  end if;

  insert into public.bookings (startup_id, slot_id, session_id, mentor_id, start_time)
  values (v_startup_id, v_slot.id, v_slot.session_id, v_slot.mentor_id, v_slot.start_time)
  returning id into v_booking_id;

  perform public.write_audit('startup', v_startup_id::text, 'book', 'bookings', v_booking_id,
                             jsonb_build_object('slot_id', v_slot.id, 'mentor_id', v_slot.mentor_id));

  return public.rpc_ok(jsonb_build_object(
    'booking_id', v_booking_id,
    'used',       v_used + 1,
    'remaining',  greatest(v_limit - (v_used + 1), 0)
  ));

exception
  when unique_violation then
    -- Final backstop. If two transactions somehow both cleared step (5), the
    -- partial unique index rejects the second INSERT. The rule holds even if
    -- the checks above are wrong.
    return public.rpc_error('SLOT_TAKEN');
end;
$$;

-- ---------------------------------------------------------------------------
-- cancel_my_booking — only when the session permits it.
-- Cancelling frees the slot automatically: availability is derived from the
-- existence of a confirmed booking, so there is no second write to forget.
-- ---------------------------------------------------------------------------
create or replace function public.cancel_my_booking(p_token text, p_booking_id uuid)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_startup_id uuid;
  v_booking    public.bookings%rowtype;
  v_session    public.sessions%rowtype;
begin
  v_startup_id := public.startup_id_from_token(p_token);
  if v_startup_id is null then
    return public.rpc_error('INVALID_SESSION');
  end if;

  select * into v_booking from public.bookings
   where id = p_booking_id and startup_id = v_startup_id
   for update;
  if not found then
    return public.rpc_error('BOOKING_NOT_FOUND');
  end if;
  if v_booking.status <> 'confirmed' then
    return public.rpc_error('ALREADY_CANCELLED');
  end if;

  select * into v_session from public.sessions where id = v_booking.session_id;
  if not v_session.allow_startup_cancellation then
    return public.rpc_error('CANCELLATION_DISABLED');
  end if;
  if v_session.status <> 'open' then
    return public.rpc_error('SESSION_CLOSED');
  end if;

  update public.bookings
     set status = 'cancelled', cancelled_at = now(), cancelled_by = 'startup'
   where id = p_booking_id;

  perform public.write_audit('startup', v_startup_id::text, 'cancel', 'bookings', p_booking_id, null);
  return public.rpc_ok();
end;
$$;

grant execute on function public.get_startup_dashboard(text)   to anon, authenticated;
grant execute on function public.book_slot(text, uuid)         to anon, authenticated;
grant execute on function public.cancel_my_booking(text, uuid) to anon, authenticated;

-- ==================== 0008_rpc_admin.sql ====================
-- ============================================================================
-- 0008 — Admin RPCs
-- ============================================================================
-- Every function begins with an is_admin() gate. Combined with 0005 (no write
-- policies on any table), this is the ONLY way anything mutates — so every
-- change is validated and audited, with no second path in.
--
-- Shared failure code: NOT_ADMIN.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Overview counters
-- ---------------------------------------------------------------------------
create or replace function public.admin_overview(p_session_id uuid default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_session_id uuid;
  v_result     jsonb;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  v_session_id := coalesce(p_session_id, public.current_session_id());

  select jsonb_build_object(
    'session_id',        v_session_id,
    'total_startups',    (select count(*) from public.startups),
    'active_startups',   (select count(*) from public.startups where is_active),
    'total_mentors',     (select count(*) from public.mentors),
    'session_mentors',   (select count(*) from public.session_mentors
                           where session_id = v_session_id and is_active),
    'total_slots',       (select count(*) from public.slots where session_id = v_session_id),
    'closed_slots',      (select count(*) from public.slots
                           where session_id = v_session_id and status = 'closed'),
    'booked_slots',      (select count(*) from public.bookings
                           where session_id = v_session_id and status = 'confirmed'),
    'available_slots',   (select count(*)
                            from public.slots sl
                            left join public.bookings b
                              on b.slot_id = sl.id and b.status = 'confirmed'
                           where sl.session_id = v_session_id
                             and sl.status = 'open'
                             and b.id is null),
    'confirmed_bookings',(select count(*) from public.bookings
                           where session_id = v_session_id and status = 'confirmed'),
    'cancelled_bookings',(select count(*) from public.bookings
                           where session_id = v_session_id and status = 'cancelled')
  ) into v_result;

  return public.rpc_ok(v_result);
end;
$$;

-- ---------------------------------------------------------------------------
-- Session management
-- ---------------------------------------------------------------------------
create or replace function public.admin_create_session(
  p_name text,
  p_session_date date default null,
  p_starts_at time default '17:00',
  p_ends_at time default '19:00',
  p_slot_minutes integer default 20,
  p_max_bookings integer default 3
)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
declare v_id uuid;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  insert into public.sessions (name, session_date, starts_at, ends_at, slot_minutes, max_bookings_per_startup)
  values (p_name, p_session_date, p_starts_at, p_ends_at, p_slot_minutes, p_max_bookings)
  returning id into v_id;

  perform public.write_audit('admin', auth.uid()::text, 'create_session', 'sessions', v_id, null);
  return public.rpc_ok(jsonb_build_object('session_id', v_id));
end;
$$;

create or replace function public.admin_update_session(
  p_session_id uuid,
  p_name text default null,
  p_session_date date default null,
  p_max_bookings integer default null,
  p_allow_cancellation boolean default null,
  p_block_duplicate_mentor boolean default null
)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  update public.sessions set
    name                       = coalesce(p_name, name),
    session_date               = coalesce(p_session_date, session_date),
    max_bookings_per_startup   = coalesce(p_max_bookings, max_bookings_per_startup),
    allow_startup_cancellation = coalesce(p_allow_cancellation, allow_startup_cancellation),
    block_duplicate_mentor     = coalesce(p_block_duplicate_mentor, block_duplicate_mentor)
  where id = p_session_id;

  if not found then return public.rpc_error('SESSION_NOT_FOUND'); end if;

  perform public.write_audit('admin', auth.uid()::text, 'update_session', 'sessions', p_session_id, null);
  return public.rpc_ok();
end;
$$;

-- Opening a session closes whichever one was open. The partial unique index
-- guarantees at most one is open; doing the swap here keeps the admin from
-- having to sequence two calls correctly under time pressure.
create or replace function public.admin_open_session(p_session_id uuid)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
declare v_session public.sessions%rowtype;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  select * into v_session from public.sessions where id = p_session_id for update;
  if not found then return public.rpc_error('SESSION_NOT_FOUND'); end if;
  if v_session.session_date is null then return public.rpc_error('SESSION_DATE_REQUIRED'); end if;
  if not exists (select 1 from public.slots where session_id = p_session_id) then
    return public.rpc_error('NO_SLOTS');
  end if;

  update public.sessions set status = 'closed' where status = 'open' and id <> p_session_id;
  update public.sessions set status = 'open'   where id = p_session_id;

  perform public.write_audit('admin', auth.uid()::text, 'open_session', 'sessions', p_session_id, null);
  return public.rpc_ok();
end;
$$;

create or replace function public.admin_close_session(p_session_id uuid)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;
  update public.sessions set status = 'closed' where id = p_session_id;
  if not found then return public.rpc_error('SESSION_NOT_FOUND'); end if;
  perform public.write_audit('admin', auth.uid()::text, 'close_session', 'sessions', p_session_id, null);
  return public.rpc_ok();
end;
$$;

-- ---------------------------------------------------------------------------
-- Mentor ↔ session assignment
-- ---------------------------------------------------------------------------
create or replace function public.admin_assign_mentors(p_session_id uuid, p_mentor_ids uuid[])
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
declare v_added integer;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  insert into public.session_mentors (session_id, mentor_id, sort_order)
  select p_session_id, m.id, m.sort_order
    from public.mentors m
   where m.id = any(p_mentor_ids)
  on conflict (session_id, mentor_id) do nothing;

  get diagnostics v_added = row_count;
  perform public.write_audit('admin', auth.uid()::text, 'assign_mentors', 'sessions', p_session_id,
                             jsonb_build_object('added', v_added));
  return public.rpc_ok(jsonb_build_object('added', v_added));
end;
$$;

-- Unassigning cascades to that mentor's slots. Refused if any of those slots
-- holds a confirmed booking — silently deleting someone's booked session is
-- never the right default.
create or replace function public.admin_unassign_mentor(p_session_id uuid, p_mentor_id uuid)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  if exists (
    select 1 from public.bookings
     where session_id = p_session_id and mentor_id = p_mentor_id and status = 'confirmed'
  ) then
    return public.rpc_error('MENTOR_HAS_BOOKINGS');
  end if;

  delete from public.session_mentors
   where session_id = p_session_id and mentor_id = p_mentor_id;
  if not found then return public.rpc_error('NOT_ASSIGNED'); end if;

  perform public.write_audit('admin', auth.uid()::text, 'unassign_mentor', 'mentors', p_mentor_id,
                             jsonb_build_object('session_id', p_session_id));
  return public.rpc_ok();
end;
$$;

-- Deactivating hides a mentor from the startup view and blocks NEW bookings.
-- Existing bookings survive — they are commitments already made to a company.
create or replace function public.admin_set_session_mentor_active(
  p_session_id uuid, p_mentor_id uuid, p_active boolean
)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  update public.session_mentors set is_active = p_active
   where session_id = p_session_id and mentor_id = p_mentor_id;
  if not found then return public.rpc_error('NOT_ASSIGNED'); end if;

  perform public.write_audit('admin', auth.uid()::text,
    case when p_active then 'activate_mentor' else 'deactivate_mentor' end,
    'mentors', p_mentor_id, jsonb_build_object('session_id', p_session_id));
  return public.rpc_ok();
end;
$$;

-- ---------------------------------------------------------------------------
-- Slot generation and control
-- ---------------------------------------------------------------------------
-- Builds the time grid from the session's own configuration (starts_at,
-- ends_at, slot_minutes) for every active assigned mentor. Idempotent, so it
-- is safe to re-run after assigning more mentors. Nothing about the number of
-- mentors or slots is hardcoded — a different event is different rows.
create or replace function public.admin_generate_slots(p_session_id uuid)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_session public.sessions%rowtype;
  v_created integer;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  select * into v_session from public.sessions where id = p_session_id;
  if not found then return public.rpc_error('SESSION_NOT_FOUND'); end if;

  insert into public.slots (session_id, mentor_id, start_time, end_time)
  select p_session_id,
         sm.mentor_id,
         g.ts::time,
         (g.ts + make_interval(mins => v_session.slot_minutes))::time
    from public.session_mentors sm
    cross join lateral (
      select generate_series(
               date '2000-01-01' + v_session.starts_at,
               date '2000-01-01' + v_session.ends_at
                 - make_interval(mins => v_session.slot_minutes),
               make_interval(mins => v_session.slot_minutes)
             ) as ts
    ) g
   where sm.session_id = p_session_id
     and sm.is_active
  on conflict (session_id, mentor_id, start_time) do nothing;

  get diagnostics v_created = row_count;
  perform public.write_audit('admin', auth.uid()::text, 'generate_slots', 'sessions', p_session_id,
                             jsonb_build_object('created', v_created));
  return public.rpc_ok(jsonb_build_object('created', v_created));
end;
$$;

-- Closing a slot that holds a confirmed booking is refused rather than
-- silently orphaning it. The admin must cancel the booking first, which is a
-- decision someone should make consciously.
create or replace function public.admin_set_slot_status(p_slot_id uuid, p_status public.slot_status)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  if p_status = 'closed' and exists (
    select 1 from public.bookings where slot_id = p_slot_id and status = 'confirmed'
  ) then
    return public.rpc_error('SLOT_HAS_BOOKING');
  end if;

  update public.slots set status = p_status where id = p_slot_id;
  if not found then return public.rpc_error('SLOT_NOT_FOUND'); end if;

  perform public.write_audit('admin', auth.uid()::text, 'set_slot_status', 'slots', p_slot_id,
                             jsonb_build_object('status', p_status));
  return public.rpc_ok();
end;
$$;

-- ---------------------------------------------------------------------------
-- Booking management
-- ---------------------------------------------------------------------------
create or replace function public.admin_cancel_booking(p_booking_id uuid, p_reason text default null)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
declare v_booking public.bookings%rowtype;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  select * into v_booking from public.bookings where id = p_booking_id for update;
  if not found then return public.rpc_error('BOOKING_NOT_FOUND'); end if;
  if v_booking.status <> 'confirmed' then return public.rpc_error('ALREADY_CANCELLED'); end if;

  update public.bookings
     set status = 'cancelled', cancelled_at = now(), cancelled_by = 'admin', cancel_reason = p_reason
   where id = p_booking_id;

  -- The slot is free again with no second write: availability is derived.
  perform public.write_audit('admin', auth.uid()::text, 'cancel_booking', 'bookings', p_booking_id,
                             jsonb_build_object('reason', p_reason));
  return public.rpc_ok();
end;
$$;

-- Moving a booking re-runs the same rules a fresh booking would face, so a
-- reassignment can never create a state that booking could not.
create or replace function public.admin_reassign_booking(p_booking_id uuid, p_new_slot_id uuid)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_booking public.bookings%rowtype;
  v_slot    public.slots%rowtype;
  v_session public.sessions%rowtype;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  select * into v_booking from public.bookings where id = p_booking_id for update;
  if not found then return public.rpc_error('BOOKING_NOT_FOUND'); end if;
  if v_booking.status <> 'confirmed' then return public.rpc_error('ALREADY_CANCELLED'); end if;

  select * into v_slot from public.slots where id = p_new_slot_id for update;
  if not found then return public.rpc_error('SLOT_NOT_FOUND'); end if;
  if v_slot.status <> 'open' then return public.rpc_error('SLOT_CLOSED'); end if;
  if v_slot.session_id <> v_booking.session_id then return public.rpc_error('CROSS_SESSION'); end if;

  if exists (select 1 from public.bookings b
              where b.slot_id = v_slot.id and b.status = 'confirmed' and b.id <> p_booking_id) then
    return public.rpc_error('SLOT_TAKEN');
  end if;

  if exists (select 1 from public.bookings b
              where b.startup_id = v_booking.startup_id
                and b.session_id = v_booking.session_id
                and b.start_time = v_slot.start_time
                and b.status = 'confirmed'
                and b.id <> p_booking_id) then
    return public.rpc_error('TIME_CONFLICT');
  end if;

  select * into v_session from public.sessions where id = v_booking.session_id;
  if v_session.block_duplicate_mentor and exists (
    select 1 from public.bookings b
     where b.startup_id = v_booking.startup_id
       and b.session_id = v_booking.session_id
       and b.mentor_id  = v_slot.mentor_id
       and b.status = 'confirmed'
       and b.id <> p_booking_id
  ) then
    return public.rpc_error('MENTOR_ALREADY_BOOKED');
  end if;

  update public.bookings
     set slot_id = v_slot.id, mentor_id = v_slot.mentor_id, start_time = v_slot.start_time
   where id = p_booking_id;

  perform public.write_audit('admin', auth.uid()::text, 'reassign_booking', 'bookings', p_booking_id,
                             jsonb_build_object('new_slot_id', p_new_slot_id));
  return public.rpc_ok();
exception
  when unique_violation then
    return public.rpc_error('SLOT_TAKEN');
end;
$$;

-- ---------------------------------------------------------------------------
-- Startup management
-- ---------------------------------------------------------------------------
create or replace function public.admin_set_startup_active(p_startup_id uuid, p_active boolean)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;
  update public.startups set is_active = p_active where id = p_startup_id;
  if not found then return public.rpc_error('STARTUP_NOT_FOUND'); end if;
  perform public.write_audit('admin', auth.uid()::text, 'set_startup_active', 'startups', p_startup_id,
                             jsonb_build_object('active', p_active));
  return public.rpc_ok();
end;
$$;

create or replace function public.admin_set_startup_limit(p_startup_id uuid, p_override integer)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;
  update public.startups set max_bookings_override = p_override where id = p_startup_id;
  if not found then return public.rpc_error('STARTUP_NOT_FOUND'); end if;
  perform public.write_audit('admin', auth.uid()::text, 'set_startup_limit', 'startups', p_startup_id,
                             jsonb_build_object('override', p_override));
  return public.rpc_ok();
end;
$$;

-- Set a specific code (used when the organiser supplies their own list).
create or replace function public.admin_set_startup_code(p_startup_id uuid, p_code text)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;
  if p_code is null or p_code !~ '^[0-9]{4}$' then return public.rpc_error('BAD_FORMAT'); end if;

  update public.startups
     set access_code_hash = extensions.crypt(p_code, extensions.gen_salt('bf', 10))
   where id = p_startup_id;
  if not found then return public.rpc_error('STARTUP_NOT_FOUND'); end if;

  -- The code itself is never logged.
  perform public.write_audit('admin', auth.uid()::text, 'set_startup_code', 'startups', p_startup_id, null);
  return public.rpc_ok();
end;
$$;

-- Generate a fresh random code and return it ONCE. Because codes are stored as
-- bcrypt hashes they cannot be read back later — reset-and-reveal is the only
-- honest affordance, and it is strictly better than a readable password column.
create or replace function public.admin_reset_startup_code(p_startup_id uuid)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_rand bytea;
  v_code text;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  v_rand := extensions.gen_random_bytes(3);
  v_code := lpad(((get_byte(v_rand,0)::int * 65536
                 + get_byte(v_rand,1)::int * 256
                 + get_byte(v_rand,2)::int) % 10000)::text, 4, '0');

  update public.startups
     set access_code_hash = extensions.crypt(v_code, extensions.gen_salt('bf', 10))
   where id = p_startup_id;
  if not found then return public.rpc_error('STARTUP_NOT_FOUND'); end if;

  perform public.write_audit('admin', auth.uid()::text, 'reset_startup_code', 'startups', p_startup_id, null);
  return public.rpc_ok(jsonb_build_object('code', v_code));
end;
$$;

-- ---------------------------------------------------------------------------
-- Mentor profile management
-- ---------------------------------------------------------------------------
create or replace function public.admin_set_mentor_active(p_mentor_id uuid, p_active boolean)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;
  update public.mentors set is_active = p_active where id = p_mentor_id;
  if not found then return public.rpc_error('MENTOR_NOT_FOUND'); end if;
  perform public.write_audit('admin', auth.uid()::text, 'set_mentor_active', 'mentors', p_mentor_id,
                             jsonb_build_object('active', p_active));
  return public.rpc_ok();
end;
$$;

create or replace function public.admin_update_mentor(
  p_mentor_id uuid,
  p_name_ar text default null,
  p_name_en text default null,
  p_bio text default null,
  p_role text default null,
  p_image_url text default null,
  p_availability_label text default null
)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  update public.mentors set
    name_ar            = coalesce(p_name_ar, name_ar),
    name_en            = coalesce(p_name_en, name_en),
    bio                = coalesce(p_bio, bio),
    role               = coalesce(p_role, role),
    image_url          = coalesce(p_image_url, image_url),
    availability_label = coalesce(p_availability_label, availability_label)
  where id = p_mentor_id;
  if not found then return public.rpc_error('MENTOR_NOT_FOUND'); end if;

  perform public.write_audit('admin', auth.uid()::text, 'update_mentor', 'mentors', p_mentor_id, null);
  return public.rpc_ok();
end;
$$;

-- Deletion is refused while any booking references the mentor, in any session,
-- cancelled or not — the record of what happened matters more than tidiness.
create or replace function public.admin_delete_mentor(p_mentor_id uuid)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  if exists (select 1 from public.bookings where mentor_id = p_mentor_id) then
    return public.rpc_error('MENTOR_HAS_BOOKINGS');
  end if;

  delete from public.mentors where id = p_mentor_id;
  if not found then return public.rpc_error('MENTOR_NOT_FOUND'); end if;

  perform public.write_audit('admin', auth.uid()::text, 'delete_mentor', 'mentors', p_mentor_id, null);
  return public.rpc_ok();
end;
$$;

-- ---------------------------------------------------------------------------
-- Grants — authenticated only. The is_admin() gate inside each function is the
-- real check; this simply keeps anon from even reaching them.
-- ---------------------------------------------------------------------------
grant execute on function public.admin_overview(uuid)                                        to authenticated;
grant execute on function public.admin_create_session(text, date, time, time, integer, integer) to authenticated;
grant execute on function public.admin_update_session(uuid, text, date, integer, boolean, boolean) to authenticated;
grant execute on function public.admin_open_session(uuid)                                    to authenticated;
grant execute on function public.admin_close_session(uuid)                                   to authenticated;
grant execute on function public.admin_assign_mentors(uuid, uuid[])                          to authenticated;
grant execute on function public.admin_unassign_mentor(uuid, uuid)                           to authenticated;
grant execute on function public.admin_set_session_mentor_active(uuid, uuid, boolean)        to authenticated;
grant execute on function public.admin_generate_slots(uuid)                                  to authenticated;
grant execute on function public.admin_set_slot_status(uuid, public.slot_status)             to authenticated;
grant execute on function public.admin_cancel_booking(uuid, text)                            to authenticated;
grant execute on function public.admin_reassign_booking(uuid, uuid)                          to authenticated;
grant execute on function public.admin_set_startup_active(uuid, boolean)                     to authenticated;
grant execute on function public.admin_set_startup_limit(uuid, integer)                      to authenticated;
grant execute on function public.admin_set_startup_code(uuid, text)                          to authenticated;
grant execute on function public.admin_reset_startup_code(uuid)                              to authenticated;
grant execute on function public.admin_set_mentor_active(uuid, boolean)                      to authenticated;
grant execute on function public.admin_update_mentor(uuid, text, text, text, text, text, text) to authenticated;
grant execute on function public.admin_delete_mentor(uuid)                                   to authenticated;

-- ==================== 0009_rpc_session_guards.sql ====================
-- ============================================================================
-- 0009 — Session guard RPCs
-- ============================================================================
-- Route guards need to answer "is this session still valid?" on every
-- navigation. Answering it with get_startup_dashboard() would drag the whole
-- mentor grid along for a yes/no, so both sides get a cheap dedicated check.
-- ============================================================================

-- Validates a startup token and returns just enough to render a header.
-- Also the single place the client learns a session has expired.
create or replace function public.startup_session_info(p_token text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_startup_id uuid;
  v_startup    public.startups%rowtype;
begin
  v_startup_id := public.startup_id_from_token(p_token);
  if v_startup_id is null then
    return public.rpc_error('INVALID_SESSION');
  end if;

  select * into v_startup from public.startups where id = v_startup_id;

  -- A company switched off mid-event loses access on its next navigation
  -- rather than at its next booking attempt.
  if not v_startup.is_active then
    return public.rpc_error('STARTUP_INACTIVE');
  end if;

  return public.rpc_ok(jsonb_build_object(
    'startup', jsonb_build_object(
      'id',       v_startup.id,
      'name_ar',  v_startup.name_ar,
      'name_en',  v_startup.name_en,
      'logo_url', v_startup.logo_url
    )
  ));
end;
$$;

-- Admin guard. is_admin() is already used inside RLS policies, but the client
-- needs to call it directly to decide whether to render the admin shell — a
-- valid Supabase Auth login that is not in admin_users must not get in.
grant execute on function public.is_admin() to authenticated;

grant execute on function public.startup_session_info(text) to anon, authenticated;

-- ==================== 0010_rpc_admin_reads.sql ====================
-- ============================================================================
-- 0010 — Admin read RPCs and per-slot management
-- ============================================================================
-- The admin UI needs shaped reads, and the admin needs to add or remove an
-- INDIVIDUAL slot rather than only regenerate a whole grid — a mentor who
-- arrives late or leaves early is a per-slot fact, not a session-wide one.
--
-- All of these carry the same is_admin() gate as 0008.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Sessions, with the counts needed to decide what to do next.
-- ---------------------------------------------------------------------------
create or replace function public.admin_list_sessions()
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare v jsonb;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', s.id, 'name', s.name, 'session_date', s.session_date,
    'starts_at', to_char(s.starts_at, 'HH24:MI'),
    'ends_at',   to_char(s.ends_at,   'HH24:MI'),
    'slot_minutes', s.slot_minutes,
    'max_bookings_per_startup', s.max_bookings_per_startup,
    'allow_startup_cancellation', s.allow_startup_cancellation,
    'block_duplicate_mentor', s.block_duplicate_mentor,
    'status', s.status,
    'mentors_assigned', (select count(*) from public.session_mentors where session_id = s.id),
    'mentors_active',   (select count(*) from public.session_mentors where session_id = s.id and is_active),
    'slots_total',      (select count(*) from public.slots where session_id = s.id),
    'bookings',         (select count(*) from public.bookings where session_id = s.id and status = 'confirmed')
  ) order by s.created_at desc), '[]'::jsonb) into v
  from public.sessions s;

  return public.rpc_ok(jsonb_build_object('sessions', v));
end;
$$;

-- ---------------------------------------------------------------------------
-- Every mentor profile, with its assignment state for one session.
-- Returns ALL profiles — assignment is a decision the admin makes here, so the
-- unassigned ones have to be visible to be assignable.
-- ---------------------------------------------------------------------------
create or replace function public.admin_list_mentors(p_session_id uuid default null)
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare v jsonb; v_session uuid;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;
  v_session := coalesce(p_session_id, public.current_session_id());

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', m.id, 'slug', m.slug, 'name_ar', m.name_ar, 'name_en', m.name_en,
    'image_url', m.image_url, 'bio', m.bio, 'role', m.role,
    'availability_label', m.availability_label,
    'is_active', m.is_active,
    'assigned',  sm.id is not null,
    'session_active', coalesce(sm.is_active, false),
    'slots_total',  (select count(*) from public.slots sl
                      where sl.session_id = v_session and sl.mentor_id = m.id),
    'slots_closed', (select count(*) from public.slots sl
                      where sl.session_id = v_session and sl.mentor_id = m.id and sl.status = 'closed'),
    'bookings',     (select count(*) from public.bookings b
                      where b.session_id = v_session and b.mentor_id = m.id and b.status = 'confirmed'),
    'organizations', (select coalesce(jsonb_agg(jsonb_build_object(
                        'name', o.org_name, 'logo_url', o.org_logo_url) order by o.sort_order), '[]'::jsonb)
                        from public.mentor_organizations o where o.mentor_id = m.id)
  ) order by m.sort_order), '[]'::jsonb) into v
  from public.mentors m
  left join public.session_mentors sm on sm.mentor_id = m.id and sm.session_id = v_session;

  return public.rpc_ok(jsonb_build_object('session_id', v_session, 'mentors', v));
end;
$$;

-- ---------------------------------------------------------------------------
-- The slot grid for a session: every slot, its state, and who holds it.
-- Unlike the startup view, this one DOES name the booking startup — that is
-- the whole point of the admin surface.
-- ---------------------------------------------------------------------------
create or replace function public.admin_list_slots(p_session_id uuid default null)
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare v jsonb; v_session uuid;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;
  v_session := coalesce(p_session_id, public.current_session_id());

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', sl.id,
    'mentor_id', sl.mentor_id,
    'mentor_name', m.name_ar,
    'start_time', to_char(sl.start_time, 'HH24:MI'),
    'end_time',   to_char(sl.end_time,   'HH24:MI'),
    'status', sl.status,
    'mentor_session_active', sm.is_active,
    'booking_id', b.id,
    'booked_by', st.name_ar
  ) order by m.sort_order, sl.start_time), '[]'::jsonb) into v
  from public.slots sl
  join public.mentors m on m.id = sl.mentor_id
  join public.session_mentors sm on sm.session_id = sl.session_id and sm.mentor_id = sl.mentor_id
  left join public.bookings b on b.slot_id = sl.id and b.status = 'confirmed'
  left join public.startups st on st.id = b.startup_id
  where sl.session_id = v_session;

  return public.rpc_ok(jsonb_build_object(
    'session_id', v_session,
    'times', coalesce((select jsonb_agg(distinct to_char(start_time, 'HH24:MI'))
                         from public.slots where session_id = v_session), '[]'::jsonb),
    'slots', v));
end;
$$;

-- ---------------------------------------------------------------------------
-- Bookings, filterable. NULL filters mean "no filter", so the UI can pass
-- whatever the user has set without composing SQL client-side.
-- ---------------------------------------------------------------------------
create or replace function public.admin_list_bookings(
  p_session_id uuid default null,
  p_startup_id uuid default null,
  p_mentor_id  uuid default null,
  p_start_time text default null,
  p_status     text default null
)
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare v jsonb; v_session uuid;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;
  v_session := coalesce(p_session_id, public.current_session_id());

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', b.id,
    'startup_id', b.startup_id, 'startup_name', st.name_ar, 'startup_logo', st.logo_url,
    'mentor_id', b.mentor_id,  'mentor_name', m.name_ar,
    'slot_id', b.slot_id,
    'start_time', to_char(b.start_time, 'HH24:MI'),
    'end_time',   to_char(sl.end_time,  'HH24:MI'),
    'session_date', se.session_date,
    'status', b.status,
    'created_at', b.created_at,
    'cancelled_at', b.cancelled_at,
    'cancelled_by', b.cancelled_by,
    'cancel_reason', b.cancel_reason
  ) order by b.start_time, st.sort_order), '[]'::jsonb) into v
  from public.bookings b
  join public.startups st on st.id = b.startup_id
  join public.mentors  m  on m.id  = b.mentor_id
  join public.slots    sl on sl.id = b.slot_id
  join public.sessions se on se.id = b.session_id
  where b.session_id = v_session
    and (p_startup_id is null or b.startup_id = p_startup_id)
    and (p_mentor_id  is null or b.mentor_id  = p_mentor_id)
    and (p_start_time is null or to_char(b.start_time, 'HH24:MI') = p_start_time)
    and (p_status     is null or b.status::text = p_status);

  return public.rpc_ok(jsonb_build_object('bookings', v));
end;
$$;

-- ---------------------------------------------------------------------------
-- Startups with their live quota for a session.
-- access_code_hash is not selected here and cannot be: no role holds the
-- column privilege (0005). Codes are set or reset, never read.
-- ---------------------------------------------------------------------------
create or replace function public.admin_list_startups(p_session_id uuid default null)
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare v jsonb; v_session uuid;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;
  v_session := coalesce(p_session_id, public.current_session_id());

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', s.id, 'slug', s.slug, 'name_ar', s.name_ar, 'name_en', s.name_en,
    'logo_url', s.logo_url, 'sector', s.sector, 'stage', s.stage, 'hq', s.hq,
    'founder_name', s.founder_name,
    'is_active', s.is_active,
    'has_code', s.access_code_hash is not null,
    'max_bookings_override', s.max_bookings_override,
    'limit', coalesce(s.max_bookings_override,
                      (select max_bookings_per_startup from public.sessions where id = v_session)),
    'used', (select count(*) from public.bookings b
              where b.startup_id = s.id and b.session_id = v_session and b.status = 'confirmed')
  ) order by s.sort_order), '[]'::jsonb) into v
  from public.startups s;

  return public.rpc_ok(jsonb_build_object('startups', v));
end;
$$;

create or replace function public.admin_audit_log(p_limit integer default 50)
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare v jsonb;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', a.id, 'actor', a.actor, 'action', a.action,
    'entity', a.entity, 'entity_id', a.entity_id,
    'detail', a.detail, 'created_at', a.created_at
  ) order by a.id desc), '[]'::jsonb) into v
  from (select * from public.audit_log order by id desc limit greatest(p_limit, 1)) a;
  return public.rpc_ok(jsonb_build_object('entries', v));
end;
$$;

-- ---------------------------------------------------------------------------
-- Per-slot management
-- ---------------------------------------------------------------------------
-- Adding one slot to one mentor. The composite FK on `slots` already refuses a
-- mentor who is not assigned to the session, so an invalid pair cannot be
-- created even if this check were removed.
create or replace function public.admin_add_slot(
  p_session_id uuid, p_mentor_id uuid, p_start_time text, p_minutes integer default null
)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_session public.sessions%rowtype;
  v_start   time;
  v_id      uuid;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  select * into v_session from public.sessions where id = p_session_id;
  if not found then return public.rpc_error('SESSION_NOT_FOUND'); end if;

  if p_start_time !~ '^[0-2][0-9]:[0-5][0-9]$' then
    return public.rpc_error('BAD_FORMAT');
  end if;
  v_start := p_start_time::time;

  if not exists (select 1 from public.session_mentors
                  where session_id = p_session_id and mentor_id = p_mentor_id) then
    return public.rpc_error('NOT_ASSIGNED');
  end if;

  insert into public.slots (session_id, mentor_id, start_time, end_time)
  values (p_session_id, p_mentor_id, v_start,
          (v_start + make_interval(mins => coalesce(p_minutes, v_session.slot_minutes))))
  on conflict (session_id, mentor_id, start_time) do nothing
  returning id into v_id;

  if v_id is null then return public.rpc_error('SLOT_EXISTS'); end if;

  perform public.write_audit('admin', auth.uid()::text, 'add_slot', 'slots', v_id,
                             jsonb_build_object('mentor_id', p_mentor_id, 'start_time', p_start_time));
  return public.rpc_ok(jsonb_build_object('slot_id', v_id));
end;
$$;

-- Deleting a slot is refused while it holds a confirmed booking. The FK from
-- bookings would refuse it anyway; failing here gives a usable reason instead
-- of a constraint violation.
create or replace function public.admin_delete_slot(p_slot_id uuid)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  if exists (select 1 from public.bookings
              where slot_id = p_slot_id and status = 'confirmed') then
    return public.rpc_error('SLOT_HAS_BOOKING');
  end if;

  delete from public.slots where id = p_slot_id;
  if not found then return public.rpc_error('SLOT_NOT_FOUND'); end if;

  perform public.write_audit('admin', auth.uid()::text, 'delete_slot', 'slots', p_slot_id, null);
  return public.rpc_ok();
end;
$$;

-- Bulk open/close for one mentor's whole row in the grid.
create or replace function public.admin_set_mentor_slots_status(
  p_session_id uuid, p_mentor_id uuid, p_status public.slot_status
)
returns jsonb
language plpgsql volatile security definer set search_path = ''
as $$
declare v_changed integer;
begin
  if not public.is_admin() then return public.rpc_error('NOT_ADMIN'); end if;

  update public.slots sl
     set status = p_status
   where sl.session_id = p_session_id
     and sl.mentor_id  = p_mentor_id
     -- Never close a slot out from under a confirmed booking.
     and (p_status = 'open'
          or not exists (select 1 from public.bookings b
                          where b.slot_id = sl.id and b.status = 'confirmed'));

  get diagnostics v_changed = row_count;
  perform public.write_audit('admin', auth.uid()::text, 'set_mentor_slots_status', 'mentors', p_mentor_id,
                             jsonb_build_object('status', p_status, 'changed', v_changed));
  return public.rpc_ok(jsonb_build_object('changed', v_changed));
end;
$$;

grant execute on function public.admin_list_sessions()                                  to authenticated;
grant execute on function public.admin_list_mentors(uuid)                               to authenticated;
grant execute on function public.admin_list_slots(uuid)                                 to authenticated;
grant execute on function public.admin_list_bookings(uuid, uuid, uuid, text, text)      to authenticated;
grant execute on function public.admin_list_startups(uuid)                              to authenticated;
grant execute on function public.admin_audit_log(integer)                               to authenticated;
grant execute on function public.admin_add_slot(uuid, uuid, text, integer)              to authenticated;
grant execute on function public.admin_delete_slot(uuid)                                to authenticated;
grant execute on function public.admin_set_mentor_slots_status(uuid, uuid, public.slot_status) to authenticated;

-- ==================== 0011_lock_down_function_grants.sql ====================
-- ============================================================================
-- 0011 — Lock down function EXECUTE grants
-- ============================================================================
-- Postgres grants EXECUTE on every new function to PUBLIC by default. The
-- explicit `grant execute ... to anon/authenticated` statements in the earlier
-- migrations therefore ADDED nothing that was not already there — and left the
-- default in place.
--
-- The practical consequences before this migration:
--
--   • anon could call every admin_* function. They are gated by is_admin() so
--     they returned NOT_ADMIN rather than acting, but an unauthenticated
--     caller could still enumerate the entire admin surface.
--
--   • anon could call write_audit() directly, which is SECURITY DEFINER and
--     inserts whatever it is handed. That is arbitrary audit-log injection:
--     an attacker could forge entries, or bury a real one under noise. The
--     audit log is the record of what happened, so a writable one is worse
--     than none.
--
--   • anon could call startup_id_from_token(), turning a stolen or guessed
--     token into a confirmed startup id without going through any RPC that
--     checks anything.
--
-- Fix: revoke from PUBLIC everywhere, then re-grant only the two intended
-- surfaces. Default privileges are changed too, so a function added later
-- fails closed rather than silently repeating this.
-- ============================================================================

revoke all on all functions in schema public from public, anon, authenticated;
revoke all on all functions in schema extensions from public, anon, authenticated;

alter default privileges in schema public revoke execute on functions from public;

-- ---------------------------------------------------------------------------
-- Public surface: everything an unauthenticated browser may call. Seven
-- functions, all of which validate their own inputs and none of which returns
-- another company's data.
-- ---------------------------------------------------------------------------
grant execute on function public.list_startups()                to anon, authenticated;
grant execute on function public.startup_login(uuid, text)      to anon, authenticated;
grant execute on function public.startup_logout(text)           to anon, authenticated;
grant execute on function public.startup_session_info(text)     to anon, authenticated;
grant execute on function public.get_startup_dashboard(text)    to anon, authenticated;
grant execute on function public.book_slot(text, uuid)          to anon, authenticated;
grant execute on function public.cancel_my_booking(text, uuid)  to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Admin surface: authenticated only, and each one still re-checks is_admin()
-- internally. The grant keeps anon from reaching them at all; the internal
-- gate is what actually authorises.
-- ---------------------------------------------------------------------------
grant execute on function public.is_admin() to authenticated;

grant execute on function public.admin_overview(uuid)                                          to authenticated;
grant execute on function public.admin_list_sessions()                                         to authenticated;
grant execute on function public.admin_list_mentors(uuid)                                      to authenticated;
grant execute on function public.admin_list_slots(uuid)                                        to authenticated;
grant execute on function public.admin_list_bookings(uuid, uuid, uuid, text, text)             to authenticated;
grant execute on function public.admin_list_startups(uuid)                                     to authenticated;
grant execute on function public.admin_audit_log(integer)                                      to authenticated;
grant execute on function public.admin_create_session(text, date, time, time, integer, integer) to authenticated;
grant execute on function public.admin_update_session(uuid, text, date, integer, boolean, boolean) to authenticated;
grant execute on function public.admin_open_session(uuid)                                      to authenticated;
grant execute on function public.admin_close_session(uuid)                                     to authenticated;
grant execute on function public.admin_assign_mentors(uuid, uuid[])                            to authenticated;
grant execute on function public.admin_unassign_mentor(uuid, uuid)                             to authenticated;
grant execute on function public.admin_set_session_mentor_active(uuid, uuid, boolean)          to authenticated;
grant execute on function public.admin_generate_slots(uuid)                                    to authenticated;
grant execute on function public.admin_set_slot_status(uuid, public.slot_status)               to authenticated;
grant execute on function public.admin_add_slot(uuid, uuid, text, integer)                     to authenticated;
grant execute on function public.admin_delete_slot(uuid)                                       to authenticated;
grant execute on function public.admin_set_mentor_slots_status(uuid, uuid, public.slot_status) to authenticated;
grant execute on function public.admin_cancel_booking(uuid, text)                              to authenticated;
grant execute on function public.admin_reassign_booking(uuid, uuid)                            to authenticated;
grant execute on function public.admin_set_startup_active(uuid, boolean)                       to authenticated;
grant execute on function public.admin_set_startup_limit(uuid, integer)                        to authenticated;
grant execute on function public.admin_set_startup_code(uuid, text)                            to authenticated;
grant execute on function public.admin_reset_startup_code(uuid)                                to authenticated;
grant execute on function public.admin_set_mentor_active(uuid, boolean)                        to authenticated;
grant execute on function public.admin_update_mentor(uuid, text, text, text, text, text, text) to authenticated;
grant execute on function public.admin_delete_mentor(uuid)                                     to authenticated;

-- ---------------------------------------------------------------------------
-- Deliberately granted to NOBODY. These are called only from inside other
-- SECURITY DEFINER functions, which run as the owner and so do not need the
-- caller to hold a grant:
--
--   write_audit            — writable audit log = forgeable history
--   startup_id_from_token  — turns a token into an identity with no checks
--   effective_max_bookings — internal quota lookup
--   current_session_id     — internal
--   rpc_ok / rpc_error     — envelope helpers
--   touch_updated_at       — trigger function
-- ---------------------------------------------------------------------------

